### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman10000**

### CODE REVIEW

**Comment by Justman10000** [comment]
@zlzleking

**Review by mary-kate — CHANGES_REQUESTED** [review]
I agree that the current wording isn't optimal. However, the proposed new wording also strikes as odd to me, given that this text is displayed on `Special:Preferences`. How about something like "`Remove the ads below the article space`" (or "article text", or...)?

**Comment by Justman10000** [comment]
> I agree that the current wording isn't optimal. However, the proposed new wording also strikes as odd to me, given that this text is displayed on `Special:Preferences`. How about something like "`Remove the ads below the article space`" (or "article text", or...)?

So... See 15f0a15

**Comment by Justman10000** [comment]
@mary-kate

**Comment by mary-kate** [comment]
Thank you! :+1:

**Pull request merged**
